name: Notificación de comentarios en problemas

on:
  issue_comment:
    types:
      - created

jobs:
  notify_on_comment:
    runs-on: e16e66fa548c
    steps:
      - name: Notificar a Dave
        run: echo "Se ha creado un comentario en un problema. ¡Notifica a Dave!"
